### ISSUE TITLE
Recommended best practice for testing services without a component

### ISSUE THREAD

**Issue by cjcoops** [testing-library/angular-testing-library#141]
Firstly thanks for the library it looks great! I'm just looking into whether Angular Testing Library would work for our team. 

I totally agree that we should be avoiding testing implementation details where possible, but we often have quite complex logic in services and sometimes there is the need to test a service (or multiple services together) without including the component, and for this situation am I right in thinking Angular Testing Library wouldn't work since `render` tests are written with the entry point of a component?

My concern is that we would be using `render` for testing when a component is involved, and then go back to using `TestBed` for testing services, which brings inconsistencies in the setup e.g. using a `setup` function for Testing Library and `beforeEach` with TestBed.

I appreciate that unit/integration testing services without a UI is not encouraged with Testing Library, but do you have any suggestions or best practices if we needed to do this? Thanks

**Comment by timdeschryver** [comment]
Hi @cjcoops , I'm happy to hear that.

Like you mentioned yourself, we focus on making component tests easier, better, and maintainable.

I haven't thought of making testing services a part of this library, because I didn't have the need for it.
Most of the service tests don't require a `TestBed, and I just instantiate them directly, e.g. `new ServiceUnderTest()` or with dependencies as `new ServiceUnderTest(dep1, dep2)`. This removes the dependency to Angular, and also makes your tests faster and easier to setup imho.

That being said, this library does have a little utility function (`createMock`) to mock services with Jest. An example can be found in the [examples](https://github.com/testing-library/angular-testing-library/blob/master/apps/example-app/app/examples/12-service-component.spec.ts#L37).

Spectator (another library to make testing easier with Angular) does support [testing services](https://github.com/ngneat/spectator#testing-services), so that might be another option.

**Comment by cjcoops** [comment]
Thanks @timdeschryver . I have experience with Spectator so I know it does the job, I just prefer the API of Testing Library and being able to avoid sharing state between tests. 

Will definitely consider whether testing services without TestBed will work though!

**Comment by timdeschryver** [comment]
FWIW, this isn't set it stone. 
If I see more questions around this, we could integrate it in this API.

**Comment by guilhermetod** [comment]
Maybe worth considering a new API now since there is no way to test the services when using the `inject` function?
