### ISSUE TITLE
Usage of toHaveFormValues with reactive forms without name attribute

### ISSUE THREAD

**Issue by rafaelss95** [testing-library/angular-testing-library#162]
Generally when we use reactive forms, we specify `formControlName`, but not `name`. Would be possible to override `toHaveFormValues` in order to avoid specify `name` for every form field?

**Comment by timdeschryver** [comment]
I'm not sure...
I would say not to override it, since it's part of [`jest-dom`](https://github.com/testing-library/jest-dom#tohaveformvalues).

We could create a new matcher in our [jest-utils](https://github.com/testing-library/angular-testing-library/tree/master/projects/jest-utils) package.
Do you think think the implementation would be an easy one? 
I also don't know how this reacts to nested/dynamic forms.

An easier approach would be to create an angular directive that sets the name?

**Comment by rafaelss95** [comment]
Hmm, I'm not also sure what the ideal solution would be, because as you said, this would be tricky for nested forms.. so the implementation would not be really easy.

I guess the directive solves the problem. Do you think it would be interesting to document that `toHaveFormValues` only works with Reactive Forms if you specify "name" or by creating a directive that replicates the `formControlName` as `name`?

**Comment by timdeschryver** [comment]
Yes, if you've lost time to investigate this problem I'm sure that adding it to the docs will help future devs 🙂
I'm just not sure where to add it, perhaps create a FAQ section?

**Comment by timdeschryver** [comment]
Closing this because #165 is merged.
Feel free to add an additional note about having a directive.
