### ISSUE TITLE
Any Idea on how to test ngIf with BehaviorSubject.

### ISSUE THREAD

**Issue by durgakiran** [testing-library/angular-testing-library#180]
**Target:**
I am writing a module where I need to hide input elements based on some conditions. I am using BehaviorSubject to maintain the toggle status.  I am trying to test it through the angular testing library.

**Problem:**
Unable to test it, the test assertion always says the input element in question is present in the document.

**Reproduction:**
Minimal reproduction is [here](https://codesandbox.io/s/cool-hoover-3uruf?file=/src/app/app.component.spec.ts). I didn't run in the codesandbox environment. I have tested this in local and then pushed to codesandbox. Here is github [repo](https://github.com/durgakiran/angular-testing).

Any help is appreciated.

**Comment by timdeschryver** [comment]
Oops, this took me a while to figure out 😅
The reason why the test fails is because the Angular change detection cycle must run to update the DOM based on the component's state. So you can call `component.detectChanges` manually in the `waitFor` expression and that should resolve the issue. 

Now the good part, is that Angular Testing Library does this for you, so I was a bit confused that it didn't work in the reproduction. After a while I noticed that `waitFor` was imported from `@testing-library/dom`, but this should be imported from `@testing-library/angular`, which triggers the change detection cycle before each "try".
In fact, you should never directly use the functionality from `dom`, but it should be used from the `angular` package.

Tip I find it easier to use `waitForElementToBeRemoved` to wait for an element to be removed.

```ts
  it('should not render div', async () => {
    const component = await render(AppComponent);
    expect(screen.queryByTestId('dummy')).toBeInTheDocument();
    await waitForElementToBeRemoved(screen.queryByTestId('dummy'));
    expect(screen.queryByTestId('dummy')).not.toBeInTheDocument();
  });
```
