### ISSUE TITLE
Routing example - fireEvent.click

### ISSUE THREAD

**Issue by ed-sparkes** [testing-library/angular-testing-library#250]
Hi, 

Is there no way to make the router tests work by simulating the user action `fireEvent.click(elem)` rather than using the `navigate(elem)` method.

Thanks, Ed

**Comment by timdeschryver** [comment]
Hi Ed, sadly this is a known issue... 
At the time when I wrote it, I didn't find a way on how to navigate to a route by simply clicking on the element.
That's why `navigate` came to life, because it picks the `href` from the route and navigates to it ([link to code](https://github.com/testing-library/angular-testing-library/blob/main/projects/testing-library/src/lib/testing-library.ts#L153-L186)).
If you know a way on how we can resolve this I'm all ears. because it's a bit cumbersome that we have to do it like this.

We could monkey-patch `click`, but eh...

**Comment by timdeschryver** [comment]
Thanks to @meirka we were able to provide a fix for this issue in #286.
I've refactored the navigation example in #287
