### ISSUE TITLE
See UI state during or after test run

### ISSUE THREAD

**Issue by meirka** [testing-library/angular-testing-library#278]
Hello, I wonder if it is possible to see what's happening with UI during a test run.

Currently I'm using Angular TestBed to test components. All tests run under jasmine in the browser, so I can actually observe UI changing or if I get stuck, I can see at which point UI stopped (given teardown after each test is turned off).

I like the idea behind this project and implementation looks very nice, but I'm having really hard time not seeing UI - makes it hard to see what's going on. 

Is there a way to see UI as test is running or stopped (finished or hit debug point)?

Thank you!

**Comment by timdeschryver** [comment]
The Testing Library isn't a test runner, it's "just" a helper to render/query/interact with a component.
That's why it can be used with jasmine or jest.

That being said, you can debug tests but it isn't a concern of this library.
I don't got much experience with it, but if you search for debugging jasmine tests, you should also be able to debug tests that use the ATL library.
