### ISSUE TITLE
Template Driven Forms

### ISSUE THREAD

**Issue by joerter** [testing-library/angular-testing-library#90]
Has anyone experienced issues with angular testing library and template driven forms? I'm seeing some behavior where it seems like form elements using ng-model are not updating. If not, I can try and reproduce what I'm seeing.

**Comment by timdeschryver** [comment]
Hi @joerter , I haven't yet seen an issue with template driven forms.
In all fairness, I'm not using template driven forms, so this will probably be a bug.

It would be helpful if you could create a reproduction for us.

**Comment by joerter** [comment]
Thanks @timdeschryver! I will see if I can reproduce the issue.

**Comment by timdeschryver** [comment]
Fyi, if you want you can create the reproduction in this repository (https://github.com/testing-library/angular-testing-library/tree/master/src/app/examples) so that we have an example (and a regression test for in the future).

Don't feel obligated to do it tho, but if you do you will first have to build the testing library with `npm run build`, to test the app run `npm run test:app`

**Comment by joerter** [comment]
Thanks! I tried to reproduce it, but things are working as they should in the template driven version of the forms example I made. I'll close this and reopen it if needed.

**Comment by timdeschryver** [comment]
Ok thanks for the update @joerter !
Don't hesitate to reopen if needed.
